// The Blender sprite pipeline (npm run blender:sprites) without child processes or the file system, so
// the tests import it as is: the registry scripts/blender/<set>/sprites.json and its checks, what each
// asset renders (frames, size, samples), the hash that tells a finished render from a stale one, the
// estimates, the dry-run text, and the run itself over effects that scripts/blender-sprites.ts wires to
// Blender, the render slot and the disk.
import {createHash} from 'node:crypto';
import path from 'node:path';

/** The loop the sprites follow: the background's 8 s at 60 fps (src/settings.ts), studio.LOOP_FRAMES in Blender. */
export const SPRITE_FPS = 60;
export const SPRITE_LOOP_FRAMES = 480;
/** Served by Remotion as staticFile('sprites/<set>/<asset>/0000.webp'); gitignored, regenerated by the script. */
export const SPRITES_ROOT = 'public/sprites';
export const BLENDER_BIN_ENV = 'BLENDER_BIN';
/** Blender 5.2, which writes WEBP with alpha, lives on the external drive. */
export const DEFAULT_BLENDER_BIN = '/Volumes/Sandisk/Applications/Blender.app/Contents/MacOS/Blender';
/** sprites.py prints its progress with this prefix, and one result line (JSON) at the end. */
export const PROGRESS_PREFIX = 'sprites:';
export const RESULT_PREFIX = 'sprites: result ';

/**
 * Disk per pixel of the square, per frame: WEBP at quality 90 with alpha, where the empty corners cost
 * little. The smoke test (heart, 128 px, 8 samples, 2026-10-07) measured 0.169 B (2.7 KiB a frame); the
 * estimate keeps the SPEC's 0.3 until a full-size render measures it.
 */
export const SPRITE_BYTES_PER_PIXEL = 0.3;
/** Cycles on Metal at 640 px and 96 samples, once the kernels are compiled: ~8 s a frame (README Known pitfalls). */
export const REFERENCE_FRAME_SECONDS = 8;
const REFERENCE_PIXELS = 640 * 640;
const REFERENCE_SAMPLES = 96;
/** What a frame costs at any size (scene update, denoiser, writing the file): 0.6 to 1.1 s on the smoke test. */
export const FRAME_OVERHEAD_SECONDS = 1;
/**
 * The first Cycles render of a Blender process compiles the Metal kernels: 100 s cold (README Known
 * pitfalls), 9.8 s on the smoke test once an earlier session had cached them. The estimate takes the cold case.
 */
export const KERNEL_COMPILE_SECONDS = 100;
/** Blender starting, the studio and the asset's mesh built before the first frame: 13 s on the smoke test. */
export const PROCESS_START_SECONDS = 15;

export type Axis = 'X' | 'Y' | 'Z';
export type SpriteMotion =
  | {kind: 'sway'; axis: Axis; degrees: number; cycles: number}
  | {kind: 'spin'; axis: Axis; turns: number; symmetry: number}
  | {kind: 'none'};
export type SpriteAsset = {
  module: string; size: number; samples: number; transparentGlass: boolean;
  pose: [number, number, number]; motion: SpriteMotion; period: number;
};
export type SpriteRegistry = {set: string; fps: number; loopFrames: number; assets: Record<string, SpriteAsset>};

const ROOT_KEYS = ['set', 'fps', 'loopFrames', 'assets'];
const ASSET_KEYS = ['module', 'size', 'samples', 'transparentGlass', 'pose', 'motion', 'period'];
const MOTION_KEYS: Record<SpriteMotion['kind'], string[]> = {
  sway: ['kind', 'axis', 'degrees', 'cycles'], spin: ['kind', 'axis', 'turns', 'symmetry'], none: ['kind'],
};
const ASSET_ID = /^[a-z][a-z0-9-]*$/;
const MODULE_NAME = /^[a-z_][a-z0-9_]*$/;

const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const isWhole = (value: unknown, min: number, max = Number.MAX_SAFE_INTEGER): value is number =>
  typeof value === 'number' && Number.isInteger(value) && value >= min && value <= max;
const gcd = (a: number, b: number): number => (b === 0 ? Math.abs(a) : gcd(b, a % b));
const shown = (value: unknown) => JSON.stringify(value) ?? String(value);
type Fail = (field: string, message: string) => void;
const under = (fail: Fail, prefix: string): Fail => (field, message) => fail(field ? `${prefix}.${field}` : prefix, message);

const parseMotion = (raw: unknown, fail: Fail): SpriteMotion | null => {
  if (!isRecord(raw)) {
    fail('', 'must be {"kind": "sway" | "spin" | "none", ...}.');
    return null;
  }
  const kind = raw.kind;
  if (kind !== 'sway' && kind !== 'spin' && kind !== 'none') {
    fail('kind', `${shown(kind)} must be "sway" (the pose ± degrees), "spin" (whole turns) or "none" (the module animates itself).`);
    return null;
  }
  let ok = true;
  const problem: Fail = (field, message) => { ok = false; fail(field, message); };
  for (const key of Object.keys(raw)) if (!MOTION_KEYS[kind].includes(key)) problem(key, `unknown field for a ${kind}; it takes ${MOTION_KEYS[kind].join(', ')}.`);
  if (kind === 'none') return ok ? {kind} : null;
  const axis = raw.axis;
  if (axis !== 'X' && axis !== 'Y' && axis !== 'Z') problem('axis', `${shown(axis)} must be "X", "Y" or "Z" (Blender's world axes, Z up).`);
  if (kind === 'sway') {
    const {degrees, cycles} = raw;
    if (typeof degrees !== 'number' || !Number.isFinite(degrees) || degrees <= 0 || degrees > 180) problem('degrees', `${shown(degrees)} must be the swing in degrees, above 0 and up to 180.`);
    if (!isWhole(cycles, 1)) problem('cycles', `${shown(cycles)} must be a whole number of swings per ${SPRITE_LOOP_FRAMES} frames (1 or more), or frame ${SPRITE_LOOP_FRAMES} would not match frame 0.`);
    return ok ? {kind, axis: axis as Axis, degrees: degrees as number, cycles: cycles as number} : null;
  }
  const {turns} = raw;
  const symmetry = raw.symmetry ?? 1;
  if (!isWhole(turns, 1)) problem('turns', `${shown(turns)} must be a whole number of turns per ${SPRITE_LOOP_FRAMES} frames (1 or more), or frame ${SPRITE_LOOP_FRAMES} would not match frame 0.`);
  if (!isWhole(symmetry, 1)) problem('symmetry', `${shown(symmetry)} must be a whole number: how many times the shape repeats in one turn (4 for a four-point star).`);
  return ok ? {kind, axis: axis as Axis, turns: turns as number, symmetry: symmetry as number} : null;
};

/** Why `period` does not bring the motion back to frame 0, or null when it does. */
const periodProblem = (motion: SpriteMotion, period: number): string | null => {
  if (motion.kind === 'sway') {
    if ((motion.cycles * period) % SPRITE_LOOP_FRAMES === 0) return null;
    const shortest = SPRITE_LOOP_FRAMES / gcd(motion.cycles, SPRITE_LOOP_FRAMES);
    return `${period} frames stop the sway mid-swing (${motion.cycles} cycle(s) per ${SPRITE_LOOP_FRAMES} frames): use ${shortest}, or a multiple of it that divides ${SPRITE_LOOP_FRAMES}.`;
  }
  if (motion.kind === 'spin') {
    const steps = motion.turns * motion.symmetry;
    if ((steps * period) % SPRITE_LOOP_FRAMES === 0) return null;
    const shortest = SPRITE_LOOP_FRAMES / gcd(steps, SPRITE_LOOP_FRAMES);
    const turned = (360 * motion.turns * period) / SPRITE_LOOP_FRAMES;
    return `after ${period} frames the spin has turned ${turned}°, and the shape (symmetry ${motion.symmetry}) looks the same only every ${360 / motion.symmetry}°: use ${shortest}, or set motion.symmetry if the shape repeats sooner.`;
  }
  // "none": the module's own drivers must repeat after the period; nothing here can see them.
  return null;
};

const parseAsset = (id: string, raw: unknown, fail: Fail): SpriteAsset | null => {
  let ok = true;
  const problem: Fail = (field, message) => { ok = false; fail(field, message); };
  if (!ASSET_ID.test(id)) problem('', `"${id}" is no usable id: lowercase letters, digits and dashes, starting with a letter (it names public/sprites/<set>/<id>/).`);
  if (!isRecord(raw)) {
    problem('', `must be an object {${ASSET_KEYS.join(', ')}}.`);
    return null;
  }
  for (const key of Object.keys(raw)) if (!ASSET_KEYS.includes(key)) problem(key, `unknown field; an asset takes ${ASSET_KEYS.join(', ')}.`);
  const {module, size, samples, transparentGlass, pose, period} = raw;
  if (typeof module !== 'string' || !MODULE_NAME.test(module)) problem('module', `${shown(module)} must name a Python module of the set folder, e.g. "heart" for heart.py.`);
  if (!isWhole(size, 16, 4096) || size % 2 !== 0) problem('size', `${shown(size)} must be the square's side, an even number of px from 16 to 4096.`);
  if (!isWhole(samples, 1, 4096)) problem('samples', `${shown(samples)} must be a whole number of Cycles samples from 1 to 4096.`);
  if (typeof transparentGlass !== 'boolean') problem('transparentGlass', 'must be true or false: true only for colourless plastic (README Known pitfalls).');
  if (!Array.isArray(pose) || pose.length !== 3 || !pose.every((angle) => typeof angle === 'number' && Number.isFinite(angle))) {
    problem('pose', `${shown(pose)} must be three rotations in degrees, [x, y, z].`);
  }
  const motion = parseMotion(raw.motion, under(problem, 'motion'));
  if (!isWhole(period, 1) || SPRITE_LOOP_FRAMES % period !== 0) {
    problem('period', `${shown(period)} must be a whole number of frames that divides ${SPRITE_LOOP_FRAMES}, e.g. ${SPRITE_LOOP_FRAMES}, 240, 160 or 120.`);
  } else if (motion) {
    const message = periodProblem(motion, period);
    if (message) problem('period', message);
  }
  if (!ok || !motion) return null;
  return {
    module: module as string, size: size as number, samples: samples as number, transparentGlass: transparentGlass as boolean,
    pose: pose as [number, number, number], motion, period: period as number,
  };
};

/** The registry, checked whole: every problem at once, each with the field and the way to fix it. */
export const parseSpriteRegistry = (data: unknown, setName: string, file = `scripts/blender/${setName}/sprites.json`): SpriteRegistry => {
  if (!isRecord(data)) throw new Error(`${file} must hold a JSON object {${ROOT_KEYS.join(', ')}}.`);
  const issues: string[] = [];
  const fail: Fail = (field, message) => issues.push(`${field}: ${message}`);
  for (const key of Object.keys(data)) if (!ROOT_KEYS.includes(key)) fail(key, `unknown field; the registry takes ${ROOT_KEYS.join(', ')}.`);
  if (data.set !== setName) fail('set', `${shown(data.set)} must be "${setName}", the name of its folder.`);
  if (data.fps !== SPRITE_FPS) fail('fps', `${shown(data.fps)} must be ${SPRITE_FPS}, the backgrounds' frame rate (src/settings.ts).`);
  if (data.loopFrames !== SPRITE_LOOP_FRAMES) fail('loopFrames', `${shown(data.loopFrames)} must be ${SPRITE_LOOP_FRAMES}: the background loop (8 s at 60 fps) and studio.LOOP_FRAMES.`);
  const assets: Record<string, SpriteAsset> = {};
  if (!isRecord(data.assets) || Object.keys(data.assets).length === 0) {
    fail('assets', `must name at least one asset: {"<id>": {${ASSET_KEYS.join(', ')}}}.`);
  } else {
    for (const [id, raw] of Object.entries(data.assets)) {
      const asset = parseAsset(id, raw, under(fail, `assets.${id}`));
      if (asset) assets[id] = asset;
    }
  }
  if (issues.length > 0) throw new Error(`${file} is invalid:\n${issues.map((issue) => `  - ${issue}`).join('\n')}`);
  return {set: setName, fps: SPRITE_FPS, loopFrames: SPRITE_LOOP_FRAMES, assets};
};

export type FrameRange = {start: number; end: number};
export type SpriteOverrides = {only?: string; frames?: string; size?: number; samples?: number};
export type PlannedSprite = {
  id: string; set: string; asset: SpriteAsset;
  /** What this run renders: the registry's values, or the smoke-test overrides. */
  size: number; samples: number; range: FrameRange;
  /** Every frame of the period at the registry's size and samples: what the composition may ship. */
  complete: boolean;
  /** Project-relative folders: the sprites, and where they render before a rename publishes them. */
  output: string; partial: string;
};

/** `start:end`, frames from start up to end (not included), inside the asset's period. */
export const parseFrameRange = (text: string, period: number, id: string): FrameRange => {
  const match = /^(\d+):(\d+)$/.exec(text);
  if (!match) throw new Error(`--frames ${text}: write start:end, the frames from start up to end, not included (e.g. 0:4).`);
  const start = Number(match[1]);
  const end = Number(match[2]);
  if (start >= end || end > period) throw new Error(`--frames ${text}: ${id} renders frames 0 to ${period - 1} (period ${period}); pick start < end ≤ ${period}.`);
  return {start, end};
};

/** The assets this run covers, in registry order, with what each renders. `pythonFiles`: the set folder's *.py names. */
export const planSprites = (registry: SpriteRegistry, overrides: SpriteOverrides, pythonFiles: readonly string[]): PlannedSprite[] => {
  const known = Object.keys(registry.assets);
  const ids = overrides.only === undefined ? known : [...new Set(overrides.only.split(',').map((id) => id.trim()).filter(Boolean))];
  if (ids.length === 0) throw new Error(`--only names no asset; ${registry.set} has ${known.join(', ')}.`);
  for (const id of ids) if (!known.includes(id)) throw new Error(`--only ${id}: no such asset in ${registry.set}; it has ${known.join(', ')}.`);
  if (overrides.size !== undefined && !(isWhole(overrides.size, 16, 4096) && overrides.size % 2 === 0)) throw new Error(`--size ${overrides.size}: an even number of px from 16 to 4096.`);
  if (overrides.samples !== undefined && !isWhole(overrides.samples, 1, 4096)) throw new Error(`--samples ${overrides.samples}: a whole number from 1 to 4096.`);
  return ids.map((id) => {
    const asset = registry.assets[id]!;
    if (!pythonFiles.includes(`${asset.module}.py`)) {
      throw new Error(`assets.${id}.module: scripts/blender/${registry.set}/${asset.module}.py does not exist; the folder has ${pythonFiles.join(', ')}.`);
    }
    const range = overrides.frames === undefined ? {start: 0, end: asset.period} : parseFrameRange(overrides.frames, asset.period, id);
    const size = overrides.size ?? asset.size;
    const samples = overrides.samples ?? asset.samples;
    const output = path.posix.join(SPRITES_ROOT, registry.set, id);
    return {
      id, set: registry.set, asset, size, samples, range,
      complete: range.start === 0 && range.end === asset.period && size === asset.size && samples === asset.samples,
      output, partial: `${output}.partial`,
    };
  });
};

/** JSON with sorted keys: the hash follows the values, not the order they were written in. */
const canonical = (value: unknown): string => {
  if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`;
  if (isRecord(value)) return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`;
  return JSON.stringify(value);
};

export type PythonFile = {name: string; content: string | Uint8Array};

/** sha256 over the asset's registry entry (with the set's fps and loop) and every Python file of the set, sorted by name. */
export const spriteHash = (registry: SpriteRegistry, id: string, pythonFiles: readonly PythonFile[]) => {
  const hash = createHash('sha256');
  hash.update(canonical({set: registry.set, fps: registry.fps, loopFrames: registry.loopFrames, id, asset: registry.assets[id]}));
  for (const file of [...pythonFiles].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))) {
    hash.update(`\0${file.name}\0`);
    hash.update(file.content);
  }
  return hash.digest('hex');
};

export type SpriteManifest = {
  asset: string; set: string;
  /** How many files: frameRange[1] - frameRange[0]. The composition shows frame (f + phase) % period. */
  frames: number; frameRange: [number, number]; period: number;
  size: number; fps: number; format: 'webp'; samples: number;
  /** false for a smoke test (fewer frames, a smaller size or fewer samples): never ship it. */
  complete: boolean;
  blender: string; scriptHash: string; createdAt: string;
};
export type SpriteDecision = {render: boolean; reason: string};

/** Skip an asset only when its manifest describes exactly this render: same hash, frames, size and samples. */
export const decideSprite = (plan: PlannedSprite, hash: string, manifest: unknown, overwrite: boolean): SpriteDecision => {
  if (overwrite) return {render: true, reason: '--overwrite'};
  if (manifest === null || manifest === undefined) return {render: true, reason: 'not rendered yet'};
  if (!isRecord(manifest)) return {render: true, reason: 'its manifest.json is unreadable'};
  if (manifest.scriptHash !== hash) return {render: true, reason: 'the registry entry or the Python changed since the last render'};
  const range = manifest.frameRange;
  const same = manifest.size === plan.size && manifest.samples === plan.samples && manifest.period === plan.asset.period
    && manifest.format === 'webp' && Array.isArray(range) && range[0] === plan.range.start && range[1] === plan.range.end;
  if (!same) {
    const frames = Array.isArray(range) ? range.join(':') : '?';
    return {render: true, reason: `rendered with other settings (frames ${frames}, ${shown(manifest.size)} px, ${shown(manifest.samples)} samples)`};
  }
  return {render: false, reason: 'up to date'};
};

/** Disk and time for one asset: frames × size² × SPRITE_BYTES_PER_PIXEL; the Metal kernels plus a cost per frame that follows pixels × samples. */
export const estimateSprite = ({size, samples, range}: Pick<PlannedSprite, 'size' | 'samples' | 'range'>) => {
  const frames = range.end - range.start;
  const frameSeconds = FRAME_OVERHEAD_SECONDS + REFERENCE_FRAME_SECONDS * ((size * size) / REFERENCE_PIXELS) * (samples / REFERENCE_SAMPLES);
  return {bytes: Math.ceil(frames * size * size * SPRITE_BYTES_PER_PIXEL), seconds: KERNEL_COMPILE_SECONDS + PROCESS_START_SECONDS + frames * frameSeconds};
};

export const formatBytes = (bytes: number) => {
  const mib = bytes / 1024 ** 2;
  if (mib < 1) return `~${Math.max(1, Math.round(bytes / 1024))} KiB`;
  if (mib >= 1024) return `~${(mib / 1024).toFixed(2)} GiB`;
  return `~${mib < 100 ? mib.toFixed(1) : Math.round(mib)} MiB`;
};

export const formatSeconds = (seconds: number) => {
  if (seconds < 60) return `~${Math.ceil(seconds)} s`;
  const minutes = Math.round(seconds / 60);
  return minutes >= 60 ? `~${Math.floor(minutes / 60)} h ${minutes % 60} min` : `~${minutes} min`;
};

export const describeMotion = (motion: SpriteMotion) => {
  if (motion.kind === 'sway') return `sway ${motion.axis} ±${motion.degrees}° ×${motion.cycles}`;
  if (motion.kind === 'spin') return `spin ${motion.axis} ×${motion.turns}${motion.symmetry > 1 ? ` (symmetry ${motion.symmetry})` : ''}`;
  return 'motion from the module';
};

export type SpriteChoice = {plan: PlannedSprite; hash: string; decision: SpriteDecision};

/** The plan as the dry run prints it: one line per asset, then what the run would render, with estimates. */
export const dryRunText = (set: string, choices: readonly SpriteChoice[], blenderStatus: string) => {
  const lines = [`Sprites ${set}: ${choices.length} asset(s). ${blenderStatus}`];
  for (const {plan, decision} of choices) {
    const what = `${plan.id}: ${plan.asset.module}.py, frames ${plan.range.start}:${plan.range.end} of ${plan.asset.period}, ${plan.size} px, ${plan.samples} samples, ${describeMotion(plan.asset.motion)} -> ${plan.output}/`;
    if (!decision.render) {
      lines.push(`  skip   ${what} (${decision.reason})`);
      continue;
    }
    const estimate = estimateSprite(plan);
    lines.push(`  render ${what} (${decision.reason}), ${formatBytes(estimate.bytes)}, ${formatSeconds(estimate.seconds)}`);
  }
  const rendering = choices.filter(({decision}) => decision.render);
  if (rendering.length === 0) {
    lines.push('Nothing to render: every asset is up to date (--overwrite renders again).');
    return lines.join('\n');
  }
  const estimates = rendering.map(({plan}) => estimateSprite(plan));
  const frames = rendering.reduce((sum, {plan}) => sum + plan.range.end - plan.range.start, 0);
  const bytes = estimates.reduce((sum, estimate) => sum + estimate.bytes, 0);
  const seconds = estimates.reduce((sum, estimate) => sum + estimate.seconds, 0);
  lines.push(`To render: ${rendering.length} asset(s), ${frames} frames, ${formatBytes(bytes)}, ${formatSeconds(seconds)} (each asset is one Blender process: ${PROCESS_START_SECONDS} s to start and up to ${KERNEL_COMPILE_SECONDS} s of Metal kernels).`);
  return lines.join('\n');
};

/** The Blender executable: BLENDER_BIN, or the Sandisk drive's; missing, a refusal with the way out. */
export const resolveBlender = (env: Readonly<Record<string, string | undefined>>, exists: (file: string) => boolean): string => {
  const given = env[BLENDER_BIN_ENV];
  if (given) {
    if (exists(given)) return given;
    throw new Error(`${BLENDER_BIN_ENV}=${given} does not exist. Point ${BLENDER_BIN_ENV} at a Blender 5.2 executable (…/Blender.app/Contents/MacOS/Blender), or unset it to use ${DEFAULT_BLENDER_BIN}.`);
  }
  if (exists(DEFAULT_BLENDER_BIN)) return DEFAULT_BLENDER_BIN;
  throw new Error(`Blender is not at ${DEFAULT_BLENDER_BIN}: connect the Sandisk drive, or set ${BLENDER_BIN_ENV} to another Blender 5.2 executable.`);
};

/** One headless Blender for one asset. --python-exit-code comes before --python: without it a Python error exits 0. */
export const blenderArgs = ({script, plan, out}: {script: string; plan: PlannedSprite; out: string}) => [
  '--factory-startup', '-b', '--python-exit-code', '1', '--python', script, '--',
  '--asset', plan.id, '--out', out, '--frames', `${plan.range.start}:${plan.range.end}`,
  '--size', String(plan.size), '--samples', String(plan.samples),
];

export type BlenderResult = {blender: string; device: string; seconds: number[]};

/** sprites.py's last line, `sprites: result {...}`; null for any other line. */
export const parseBlenderResult = (line: string): BlenderResult | null => {
  if (!line.startsWith(RESULT_PREFIX)) return null;
  const data: unknown = JSON.parse(line.slice(RESULT_PREFIX.length));
  if (!isRecord(data) || typeof data.blender !== 'string' || !Array.isArray(data.seconds) || !data.seconds.every((value) => typeof value === 'number')) {
    throw new Error(`sprites.py printed a malformed result line: ${line}`);
  }
  return {blender: data.blender, device: typeof data.device === 'string' ? data.device : '?', seconds: data.seconds as number[]};
};

export type WebpInfo = {width: number; height: number; alpha: boolean};

/** Width, height and alpha from a WEBP file's first chunk (VP8X, VP8L or VP8); null when the bytes are no WEBP. */
export const readWebpInfo = (data: Uint8Array): WebpInfo | null => {
  if (data.length < 30) return null;
  const text = (start: number, length: number) => String.fromCharCode(...data.subarray(start, start + length));
  if (text(0, 4) !== 'RIFF' || text(8, 4) !== 'WEBP') return null;
  const byte = (at: number) => data[at] ?? 0;
  const u24 = (at: number) => byte(at) | (byte(at + 1) << 8) | (byte(at + 2) << 16);
  const chunk = text(12, 4);
  // Extended: flags at 20 (alpha 0x10), canvas width - 1 and height - 1 in 24 bits at 24 and 27.
  if (chunk === 'VP8X') return {width: u24(24) + 1, height: u24(27) + 1, alpha: (byte(20) & 0x10) !== 0};
  if (chunk === 'VP8L') {
    // Lossless: signature 0x2f at 20, then width - 1 (14 bits), height - 1 (14 bits) and the alpha bit.
    const bits = (byte(21) | (byte(22) << 8) | (byte(23) << 16) | (byte(24) << 24)) >>> 0;
    return {width: (bits & 0x3fff) + 1, height: ((bits >>> 14) & 0x3fff) + 1, alpha: ((bits >>> 28) & 1) === 1};
  }
  // Simple lossy: no alpha at all.
  if (chunk === 'VP8 ') return {width: (byte(26) | (byte(27) << 8)) & 0x3fff, height: (byte(28) | (byte(29) << 8)) & 0x3fff, alpha: false};
  return null;
};

export const frameName = (frame: number) => `${String(frame).padStart(4, '0')}.webp`;

export type SpriteEffects = {
  /** The Blender executable (resolveBlender); asked once, before the first asset that renders. */
  findBlender: () => string;
  /** Waits for the machine and takes the render slot, with the disk floor checked for `estimateBytes` once it is held. */
  takeTurn: (plan: PlannedSprite, estimateBytes: number) => Promise<{release: () => void}>;
  /** Removes the project-relative folder if it is there and creates it empty. */
  resetDirectory: (relative: string) => Promise<void>;
  runBlender: (blender: string, args: string[]) => Promise<BlenderResult>;
  /** The frame's WEBP header and its size in bytes; null when the file is missing. */
  readFrame: (relative: string) => Promise<{info: WebpInfo | null; bytes: number} | null>;
  writeJson: (relative: string, data: unknown) => Promise<void>;
  /** Replaces the folder `to` with `from`: a rename, so the sprites appear whole or not at all. */
  publish: (from: string, to: string) => Promise<void>;
  log: (message: string) => void;
  now: () => Date;
};

export type SpriteRunResult = {
  id: string; frames: number; wallSeconds: number; frameSeconds: number[]; bytes: number; bytesPerPixel: number; blender: string; device: string;
};

/**
 * Renders the chosen assets one by one: each takes its own render turn (never one around the chain, so
 * another render waiting gets the machine between two assets), renders into `<asset>.partial/`, has
 * every frame checked (a WEBP with alpha at the planned size), gets its manifest and is renamed into place.
 */
export const runSprites = async ({choices, root, script, effects}: {
  choices: readonly SpriteChoice[]; root: string; script: string; effects: SpriteEffects;
}): Promise<SpriteRunResult[]> => {
  const results: SpriteRunResult[] = [];
  let blender: string | undefined;
  for (const {plan, hash, decision} of choices) {
    if (!decision.render) {
      effects.log(`${plan.id}: skipped, ${decision.reason}.`);
      continue;
    }
    // Before the first turn: a missing drive is refused before anything waits or renders.
    blender ??= effects.findBlender();
    const estimate = estimateSprite(plan);
    const frames = plan.range.end - plan.range.start;
    effects.log(`${plan.id}: ${frames} frames (${plan.range.start}:${plan.range.end}) at ${plan.size} px and ${plan.samples} samples, ${decision.reason}; estimate ${formatBytes(estimate.bytes)}, ${formatSeconds(estimate.seconds)}.`);
    const turn = await effects.takeTurn(plan, estimate.bytes);
    try {
      await effects.resetDirectory(plan.partial);
      const started = effects.now().getTime();
      const result = await effects.runBlender(blender, blenderArgs({script, plan, out: path.join(root, plan.partial)}));
      const wallSeconds = (effects.now().getTime() - started) / 1000;
      let bytes = 0;
      for (let frame = plan.range.start; frame < plan.range.end; frame++) {
        const file = path.posix.join(plan.partial, frameName(frame));
        const read = await effects.readFrame(file);
        if (read === null) throw new Error(`${plan.id}: Blender wrote no ${file}. Run again: the asset renders from the start.`);
        const {info} = read;
        if (info === null || info.width !== plan.size || info.height !== plan.size || !info.alpha) {
          const found = info === null ? 'no WEBP header' : `${info.width}×${info.height}, ${info.alpha ? 'with' : 'without'} alpha`;
          throw new Error(`${plan.id}: ${file} is not a ${plan.size}×${plan.size} WEBP with alpha (${found}). Check use_webp in sprites.py.`);
        }
        bytes += read.bytes;
      }
      const manifest: SpriteManifest = {
        asset: plan.id, set: plan.set, frames, frameRange: [plan.range.start, plan.range.end], period: plan.asset.period,
        size: plan.size, fps: SPRITE_FPS, format: 'webp', samples: plan.samples, complete: plan.complete,
        blender: result.blender, scriptHash: hash, createdAt: effects.now().toISOString(),
      };
      await effects.writeJson(path.posix.join(plan.partial, 'manifest.json'), manifest);
      await effects.publish(plan.partial, plan.output);
      const bytesPerPixel = bytes / (frames * plan.size * plan.size);
      const [first = 0, ...rest] = result.seconds;
      const then = rest.length > 0 ? `, then ${(rest.reduce((sum, value) => sum + value, 0) / rest.length).toFixed(1)} s a frame` : '';
      effects.log(`${plan.id}: ${frames} frames in ${wallSeconds.toFixed(1)} s (Blender ${result.blender}, ${result.device}; first frame ${first.toFixed(1)} s with the Metal kernels${then}), ${(bytes / frames / 1024).toFixed(1)} KiB a frame (${bytesPerPixel.toFixed(3)} B/px) -> ${plan.output}/`);
      results.push({id: plan.id, frames, wallSeconds, frameSeconds: result.seconds, bytes, bytesPerPixel, blender: result.blender, device: result.device});
    } finally {
      turn.release();
    }
  }
  return results;
};
